version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: site_frontend
    ports:
      - "8083:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: site_backend
    ports:
      - "3002:3000"
